default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: recipe_finder_development

test:
  <<: *default
  database: recipe_finder_test

production:
  <<: *default
  database: recipe_finder_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
